SOL/Calendar/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout

urlpatterns = patterns('Calendar.views',
	url(r'^$', 'index'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', 'day_events'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<eid>\d+)/$', 'update_event'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<eid>\d+)/remove/$', 'remove_event'),
	url(r'^event/$', 'event'),
	url(r'^event/label/$', 'label'),
	url(r'^event/label/(?P<lid>\d+)/$', 'update_label'),
)

SOL/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', include('Main.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),

	url(r'^accounts/', include('Main.urls')),
	
	url(r'^calendar/', include('Calendar.urls')),
		
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/instructor/', include('Instructor.urls')),
	
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/grades/', include('Gradebook.urls')),
		
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/forum/', include('Forum.urls')),
	
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/', include('Student.urls')),


)

SOL/Calendar/models.py
#Calendar Model
from django.db import models
from django.forms import ModelForm
from Main.models import UserProfile
from Instructor.models import Activity

# Create your models here.
class Label(models.Model):
	COLOR_CHOICES = (
		(u'Red', u'Red'),
		(u'Orange', u'Orange'),
		(u'Yellow', u'Yellow'),
		(u'Green', u'Green'),
		(u'DarkBlue', u'Dark Blue'),
		(u'LightBlue', u'Light Blue'),
		(u'Purple', u'Purple'),
		(u'Black', u'Black'),
		(u'Gray', u'Gray'),
	)
	
	lid = models.AutoField(primary_key=True)
	name = models.CharField(max_length=256)
	color = models.CharField(max_length=32, choices=COLOR_CHOICES)
	uid = models.ForeignKey(UserProfile, verbose_name='SFU ID')
	cid = models.IntegerField(blank=True, null=True)
	def __unicode__(self):
		return '(' + self.color +') '+ self.name

class Event(models.Model):	
	eid = models.AutoField(primary_key=True)
	lid = models.ForeignKey(Label, verbose_name='Label')
	uid = models.ForeignKey(UserProfile, verbose_name='SFU ID')
	cid = models.IntegerField(blank=True, null=True)
	event_name = models.CharField(max_length=64)
	date = models.DateTimeField()
	location = models.CharField(max_length=64, blank=True)
	description = models.TextField(blank=True)

SOL/Calendar/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import ModelChoiceField
from Calendar.models import Event, Label
import datetime

# Create your models here.
class EventForm(ModelForm):
	def __init__(self, *args, **kwargs):
		uid=kwargs.pop('uid')
		super(EventForm, self).__init__(*args, **kwargs)
		self.fields['lid'] = ModelChoiceField(queryset=Label.objects.filter(uid=uid), empty_label="<Choose Label>")
	
	class Meta:
		model = Event
		exclude = ('uid', 'cid',)

class LabelForm(ModelForm):
	class Meta:
		model = Label
		exclude = ('cid', 'uid', )
		
class CalendarForm(forms.Form):
	MONTH_CHOICES = (
		(1, u'January'),
		(2, u'February'),
		(3, u'March'),
		(4, u'April'),
		(5, u'May'),
		(6, u'June'),
		(7, u'July'),
		(8, u'August'),
		(9, u'September'),
		(10, u'October'),
		(11, u'November'),
		(12, u'December'),
	)
	
	YEAR_CHOICES = (
		(2011, u'2011'),
		(2012, u'2012'),
		(2013, u'2013'),
		(2014, u'2014'),
		(2015, u'2015'),
		(2016, u'2016'),
		(2017, u'2017'),
		(2018, u'2018'),
		(2019, u'2019'),
		(2020, u'2020'),
		(2021, u'2021'),
		(2022, u'2022'),
		(2023, u'2023'),
		(2024, u'2024'),
		(2025, u'2025'),
	)
	
	month = forms.ChoiceField(choices=MONTH_CHOICES, initial=datetime.datetime.now().month)
	year = forms.ChoiceField(choices=YEAR_CHOICES, initial=datetime.datetime.now().year)

SOL/Calendar/views.py
# Calendar Views
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext, Context
from itertools import chain
from operator import attrgetter
import calendar, datetime, random

from Main.views import getGlobalAnnouncements
from Student.views import getClassList, getStudents
from Calendar.models import Event, Label
from Calendar.forms import EventForm, LabelForm, CalendarForm

#View to generate the page for the main view of Calendar App
def index(request):
	class_list = getClassList(request.user)
	
	cal = calendar.Calendar(6)
	curr_date = datetime.datetime.today()
	
	month_name = { '1': 'January', '2': 'February', '3': 'March', '4': 'April', '5': 'May', '6': 'June', '7': 'July', '8': 'August', '9': 'September', '10': 'October', '11': 'November', '12': 'December' }		
	
	if request.method == 'POST':
		form = CalendarForm(request.POST)
		if form.is_valid():
			curr_month = int(request.POST.__getitem__('curr_month'))
			curr_year = int(request.POST.__getitem__('curr_year'))
			# If previous month is selected, get the previous month and associated year
			if 'prev_month' in request.POST:
				prev_month = curr_month - 1
				if prev_month == 0:
					prev_month = 12
					year = curr_year - 1
				else:
					year = curr_year
				month = { 'name': month_name[str(prev_month)], 'number': prev_month }
				all_weeks = getCalendar(cal, year, month['number'])
			# Else if next month is selected, get the next month and associated year
			elif 'next_month' in request.POST:
				next_month = curr_month + 1
				if next_month == 13:
					next_month = 1
					year = curr_year + 1
				else:
					year = curr_year
				month = { 'name': month_name[str(next_month)], 'number': next_month }
				all_weeks = getCalendar(cal, year, month['number'])
			# Otherwise, return the current month and associated year
			else:
				year = int(form.cleaned_data['year'])
				month = { 'name': month_name[form.cleaned_data['month']], 'number': int(form.cleaned_data['month']) }
			all_weeks = getCalendar(cal, year, month['number'])
			days_with_events = getEvents(request.user, class_list, year, month['number'])
	else:
		form = CalendarForm()
		all_weeks = getCalendar(cal, curr_date.year, curr_date.month)
		year = curr_date.year
		month = {'name': curr_date.strftime("%B"), 'number': curr_date.month }
		days_with_events = getEvents(request.user, class_list, year, month['number'])
		
	context = { 'form': form, 'days_with_events': days_with_events, 'all_weeks': all_weeks, 'year': year, 'month': month, 
		'globalAnnouncements': getGlobalAnnouncements(request.user), 'class_list': class_list }
	return render_to_response('calendar/index.html', context, RequestContext(request))

# View for displaying all events for a particular day
def day_events(request, year, month, day):
	class_list = getClassList(request.user)
	
	month_name = { '1': 'January', '2': 'February', '3': 'March', '4': 'April', '5': 'May', '6': 'June', '7': 'July', '8': 'August', '9': 'September', '10': 'October', '11': 'November', '12': 'December' }		
	
	month_name = month_name[month]
	selected_day = { 'year': year, 'month': month_name, 'day': day }

	# Get all events created by the user for the specified day
	custom_events = Event.objects.filter(uid=request.user, date__year=year, date__month=month, date__day=day).order_by('date')
	
	# Get all events for that day for the classes for which the student is enrolled in
	events_chain = chain(custom_events)
	for course in class_list:
		if request.user.userprofile in getStudents(course.cid):
			events_chain = chain(Event.objects.filter(cid=course.cid, date__year=year, date__month=month, date__day=day), events_chain)
	
	# Chain all events retrieved into one events queryset
	events = sorted(events_chain, key=attrgetter('date'))
	
	context = { 'events': events, 'selected_day': selected_day, 'globalAnnouncements': getGlobalAnnouncements(request.user),
		'class_list': class_list }
	return render_to_response('calendar/day_events.html', context, RequestContext(request))

# View for creating a new event
def event(request):
	class_list = getClassList(request.user)
	label_error = ''
	if request.method == 'POST':
		form = EventForm(request.POST, uid=request.user.id)
		if 'update_label' in request.POST:
			if form.cleaned_data['lid']:
				label = Label.objects.get(lid=request.POST['lid'])
				# Check to see if the label is associated to a class
				if label.cid:
					form = EventForm(uid=request.user.id)
					label_error = 'You cannot edit that course label'
				else:
					return HttpResponseRedirect("/calendar/event/label/" + request.POST['lid'])
			else:
				form = EventForm(uid=request.user.id)
				label_error = 'Please choose a label to edit'
		elif 'create_label' in request.POST:
			return HttpResponseRedirect("/calendar/event/label/")
		elif form.is_valid():
			event_name = form.cleaned_data['event_name']
			date = form.cleaned_data['date']
			location = form.cleaned_data['location']
			label = Label.objects.get(lid=request.POST['lid'])
			description = form.cleaned_data['description']
			event = Event(uid=request.user.userprofile, event_name=event_name, date=date, location=location, lid=label, description=description)
			event.save()
			return HttpResponseRedirect("/calendar")
	else:
		form = EventForm(uid=request.user.id)
	
	update = 0
	context = { 'form': form, 'label_error': label_error, 'update': update, 'globalAnnouncements': getGlobalAnnouncements(request.user),
	 	'class_list': class_list }
	return render_to_response('calendar/event.html', context, RequestContext(request))

# View for updating an existing event
def update_event(request, year, month, day, eid):
	class_list = getClassList(request.user)
	if request.method == 'POST':
		lid = Label.objects.get(lid=request.POST['lid'])
		event = Event(uid=request.user.userprofile, eid=eid, lid=lid)
		form = EventForm(request.POST, uid=request.user.userprofile, instance=event)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect("..")
	else:
		tmp = Event.objects.get(eid=eid)
		existing_event = { 'lid': tmp.lid, 'event_name': tmp.event_name, 'date': tmp.date, 'location': tmp.location, 'description': tmp.description }
		form = EventForm(uid=request.user.id, initial=existing_event)
		
	update = 1
	context = { 'form': form, 'update': update, 'globalAnnouncements': getGlobalAnnouncements(request.user),
	 	'class_list': class_list }
	return render_to_response('calendar/event.html', context, RequestContext(request))

# View for removing an existing event
def remove_event(request, year, month, day, eid):
	event = Event.objects.get(eid=eid)
	event.delete()
	return HttpResponseRedirect("/calendar/%s" %year + '/%s' %month + '/%s' %day)

# View for creating a label
def label(request):
	class_list = getClassList(request.user)
	if request.method == 'POST':
		form = LabelForm(request.POST)
		if 'update_label' in request.POST:
			return HttpResponseRedirect("/calendar/event/" + request.POST['lid'])
		elif form.is_valid():
			user = request.user
			label_name = form.cleaned_data['name']
			color = form.cleaned_data['color']
			label = Label(uid=user.userprofile, name=label_name, color=color)
			label.save()
			return HttpResponseRedirect("/calendar/event")
	else:
		form = LabelForm()
		
	update = 0
	context = { 'form': form, 'update': update, 'globalAnnouncements': getGlobalAnnouncements(request.user),
	 	'class_list': class_list }
	return render_to_response('calendar/label.html', context, RequestContext(request))

# View for updating a label
def update_label(request, lid):
	class_list = getClassList(request.user)
	if request.method == 'POST':
		label = Label(uid=request.user.userprofile, lid=lid)
		form = LabelForm(request.POST, instance=label)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect("/calendar/event")
	else:
		tmp = Label.objects.get(lid=lid)
		form = LabelForm(initial={ 'name': tmp.name, 'color': tmp.color })
		
	update = 1
	context = { 'form': form, 'update': update, 'globalAnnouncements': getGlobalAnnouncements(request.user),
	 	'class_list': class_list }
	return render_to_response('calendar/label.html', context, RequestContext(request))

# Method to retrieve a calendar
def getCalendar(cal, year, month):
	cal_month = cal.itermonthdays(year, month)
	all_weeks = []
	week = []
	count = 0
	for day in cal_month:
		week.append(day)
		count = count + 1
		if count == 7:
			all_weeks.append(week)
			week = []
			count = 0
	return all_weeks

# Method to get the events for a month
def getEvents(user, class_list, year, month):
	# Get all events created by the user
	custom_events = Event.objects.filter(uid=user, date__year=year, date__month=month).order_by('date')
	
	# Get all events for the classes for which the student is enrolled in
	events_chain = chain(custom_events)
	for course in class_list:
		if user.userprofile in getStudents(course.cid):
			events_chain = chain(Event.objects.filter(cid=course.cid, date__year=year, date__month=month), events_chain)
	
	# Chain all events retrieved into one events queryset
	events = sorted(events_chain, key=attrgetter('date'))
	
	day_of_month = range(1, calendar.monthrange(year, month)[1]+1)
	days_with_events = {}
	
	def getEventsForDay(event):
		if event.date.day == day:
			return event
	
	for day in day_of_month:
		all_days_events = filter(getEventsForDay, events)
		if all_days_events:
			if all_days_events.count <= 4:
				limit_events = all_days_events
			elif all_days_events.count > 4:
				limit_events = all_days_events[:4]
			for event in limit_events:
				# Don't count the first 5 spaces as characters in the length of the event name
				tempLength = event.event_name.replace(' ', '', 5)
				if len(tempLength) > 8:
					event.event_name = event.event_name[:8] + '...'
			days_with_events[day] = { 'limit': limit_events, 'all': all_days_events, 'total': len(all_days_events) }

	return days_with_events

SOL/templates/calendar/day_events.html
{% extends "base.html" %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/calendar.css">
{% endblock %}

{% block sidebar %}
	{% if flavour == "full" %}
		<h2 class="title">Announcements</h2>
		{% if globalAnnouncements.count > 0 %}
			{% for announcement in globalAnnouncements %}
				<div class="announceTitle">
					{{ announcement.cid.department }} {{ announcement.cid.class_number }}: {{ announcement.title }} 
					{% if announcement.isNew %}
						<img src="/static/images/new.png" alt="back"> 
					{% endif %}
				</div>
				<div class="announceContent">
					{{ announcement.content }}
				</div>
			{% endfor %}
		{% else %}
			<div class="announceContent">
				No announcements
			</div>
		
		{% endif %}
	{% endif %}
{% endblock %}

{% block content %}
	<h2 class="title">{{ selected_day.month }} {{ selected_day.day }}, {{ selected_day.year }} - Events</h2>
	<p class="back"><span class="linkButton"><a href="/calendar">Back to Calendar</a></span></p>
	
	{% for event in events %}
		<div class="table">
			<div class="postTop">
				<font color="{{ event.lid.color }}">
					{{ event.date|date:"g:i a" }}
					({{ event.lid.name }})
				</font>
				<strong>{{ event.event_name }}</strong>
				{% if event.location %}
					<span class="postDate"> - {{ event.location }}</span>
				{% endif %}
				<span class="postLinks">
					{% if not event.cid %}
						<span class="linkButton"><a href="{{ event.eid }}">Edit</a></span> <span class="linkButton"><a href="{{ event.eid }}/remove">Remove</a></span>
					{% endif %}
				</span>
			</div>
			<div class="postMiddle">
				<span class="postDate">Created by: {{ event.uid.user.first_name }} {{ event.uid.user.last_name }}
			</div>
			<div class="postBottom">
				{{ event.description }}
			</div>
		</div>
	{% endfor %}
	
{% endblock %}

SOL/templates/calendar/event.html
{% extends "base.html" %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/calendar.css">	
	<link type="text/css" href="{{ STATIC_URL }}css/timepicker.css" rel="Stylesheet" />
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>
		
{% endblock %}

{% block sidebar %}
	{% if flavour == "full" %}
		<h2 class="title">Announcements</h2>
		{% if globalAnnouncements.count > 0 %}
			{% for announcement in globalAnnouncements %}
				<div class="announceTitle">
					{{ announcement.cid.department }} {{ announcement.cid.class_number }}: {{ announcement.title }} 
					{% if announcement.isNew %}
						<img src="/static/images/new.png" alt="back"> 
					{% endif %}
				</div>
				<div class="announceContent">
					{{ announcement.content }}
				</div>
			{% endfor %}
		{% else %}
			<div class="announceContent">
				No announcements
			</div>
		
		{% endif %}
	{% endif %}
{% endblock %}


{% block content %}
	<script type="text/javascript">
		$(function() {
	    	$('#id_date').datetimepicker({
				dateFormat: "yy-mm-dd"
			});
		});
	</script>
	
	{% if update %}
		<h2 class="title">Update Event Form</h2>
		<p class="back"><span class="linkButton"><a href="..">Back To Events</a></span></p>
	{% else %}
		<h2 class="title">Create New Event</h2>
		<p class="back"><span class="linkButton"><a href="/calendar">Back to Calendar</a></span></p>
	{% endif %}
	
	<font color="red">{{ label_error }}</font>
	<form action="" method="POST">
		<div class="table">
		{% csrf_token %}
			{% for field in form %}
			<div class="fieldWrapper">
				<div class="fieldLeft">
					{% if 'Lid' in field.label_tag %}
						Label: 
					{% else %}
						{{ field.label_tag }}:
					{% endif %}
				</div>
					<div class="fieldRight">
						{{ field.errors }}
						{{ field }}
						
						{% if 'Lid' in field.label_tag %}
							{% if not update %}
								<input class="sideFieldButton" type="submit" name="create_label" value="Create Label">
								<input class="sideFieldButton" type="submit" name="update_label" value="Edit Label">
							{% endif %}
						{% endif %}
					</div>
			</div>
			{% endfor %}
			<div class="submit">
				{% if update %}
					<input type="submit" value="Update">
				{% else %}
					<input type="submit" value="Submit">
				{% endif %}
			</div>
		</div>
	</form>

{% endblock %}

SOL/templates/calendar/index.html
{% extends "base.html" %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/calendar.css">
{% endblock %}

{% if flavour == "mobile" %}
	
{% else %}
	{% block sidebar %}
	{% load calendar_extras %}
		{% if flavour == "full" %}
			<h2 class="title">Announcements</h2>
			{% if globalAnnouncements.count > 0 %}
				{% for announcement in globalAnnouncements %}
					<div class="announceTitle">
						{{ announcement.cid.department }} {{ announcement.cid.class_number }}: {{ announcement.title }} 
						{% if announcement.isNew %}
							<img src="/static/images/new.png" alt="back"> 
						{% endif %}
					</div>
					<div class="announceContent">
						{{ announcement.content }}
					</div>
				{% endfor %}
			{% else %}
				<div class="announceContent">
					No announcements
				</div>

			{% endif %}
		{% endif %}
		
	{% endblock %}
	
	{% block content %}
		{% if flavour == "full" %}
		{% load calendar_extras %}
		<div id="cal_header">
			<div id="cal_header_left">
				<span class="linkButton"><a href="event">Create New Event</a></span>
			</div>
			<div id="cal_header_right">
				<div id="head_date">
					<form action="" method="POST">
						{% csrf_token %}
						{% for field in form %}
							{{ field }} {{ field.errors }}
						{% endfor %}
						<input type="submit" name="change_month" value="Change Month">
						<input type="submit" name="prev_month" value="<<" />
						<input type="submit" name="next_month" value=">>" />
						<input type="hidden" name="curr_year" value="{{ year }}" />
						<input type="hidden" name="curr_month" value="{{ month.number }}" />
					</form>
				</div>
				<div id="head_month">
					<h1>{{ month.name }} {{ year }}</h1>
				</div>
			</div>
		</div>
		
	    <table id="cal_table" border="0" cellpadding="0" cellspacing="0">
	    	<tr id="weekdays">
	    		<td class="dayname">Sunday</td>
	    		<td class="dayname">Monday</td>
	    		<td class="dayname">Tuesday</td>
	    		<td class="dayname">Wednesday</td>
	    		<td class="dayname">Thursday</td>
	    		<td class="dayname">Friday</td>
	    		<td class="dayname">Saturday</td>
	    	</tr>
	    	{% for week in all_weeks %}
	    		<tr>
	    			{% for day in week %}
	    				{% if day == 0 %}
	    					<td class="day"></td>
	    				{% else %}
							{% if day in days_with_events %}
								<td class="day">
									<a href="/calendar/{{ year }}/{{ month.number }}/{{ day }}/">
										<div class="dayTop">
											{{ day }}
										</div>
										<div class="dayBottom">
											<ul>
												{% for event in days_with_events|get_key_value:day|get_key_value:'limit' %}
													<font color="{{ event.lid.color }}"><li>{{ event.event_name }}</li></font>
												{% endfor %}
												{% if days_with_events|get_key_value:day|get_key_value:'total' > 4 %}
													<li>. . .</li>
												{% endif %}
											</ul>
										</div>
									</a>
								</td>
							{% else %}
								<td class="day">
									{{ day }}
								</td>
							{% endif %}
	    				{% endif %}
	    			{% endfor %}
	    		</tr>
	    	{% endfor %}

	    </table> 
	{% endif %}
	{% endblock %}
{% endif %}

SOL/templates/calendar/label.html
{% extends "base.html" %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/calendar.css">
{% endblock %}

{% block sidebar %}
	{% if flavour == "full" %}
		<h2 class="title">Announcements</h2>
		{% if globalAnnouncements.count > 0 %}
			{% for announcement in globalAnnouncements %}
				<div class="announceTitle">
					{{ announcement.cid.department }} {{ announcement.cid.class_number }}: {{ announcement.title }} 
					{% if announcement.isNew %}
						<img src="/static/images/new.png" alt="back"> 
					{% endif %}
				</div>
				<div class="announceContent">
					{{ announcement.content }}
				</div>
			{% endfor %}
		{% else %}
			<div class="announceContent">
				No announcements
			</div>
		
		{% endif %}
	{% endif %}
{% endblock %}

{% block content %}

	{% if update %}
		<h2 class="title">Update Label Form</h2>
	{% else %}
		<h2 class="title">Create New Label</h2>
	{% endif %}
	
	<p class="back"><span class="linkButton"><a href="/calendar/event">Back to Create New Event</a></span></p>
	
	<form action="" method="POST">
		<div class="table">
		{% csrf_token %}
			{% for field in form %}
			<div class="fieldWrapper">
				<div class="fieldLeft">
					{{ field.label_tag }}:
				</div>
					<div class="fieldRight">
						{{ field.errors }}
						{{ field }}
					</div>
			</div>
			{% endfor %}
			<div class="submit">
				<input type="submit" value="Submit">
			</div>
		</div>
	</form>

{% endblock %}