SOL/Forum/urls.py
from django.conf.urls.defaults import patterns, include, url
from Forum.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('Forum.views',
	url(r'^$', 'topic_display'),
	url(r'^(?P<topic_id>\d+)/$', 'message_display'),
	url(r'^(?P<topic_id>\d+)/delete/$', 'remove_topic'),
)

SOL/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', include('Main.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),

	url(r'^accounts/', include('Main.urls')),
	
	url(r'^calendar/', include('Calendar.urls')),
		
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/instructor/', include('Instructor.urls')),
	
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/grades/', include('Gradebook.urls')),
		
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/forum/', include('Forum.urls')),
	
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/', include('Student.urls')),


)

SOL/Forum/models.py
from django.db import models
from SOL.Main.models import Course

# topics created per course...
class Topics(models.Model):
	topic_name = models.CharField(max_length = 125)
	course = models.ForeignKey(Course)
	# if show is false, means it is deleted
	not_deleted = models.BooleanField(default = True) 

	def __unicode__(self):
		return self.topic_name

class Messages(models.Model):
	topic = models.ForeignKey(Topics)	# list of msgs for a topic
	user = models.CharField(max_length=100)	# user who posted
	# need to have a post number for that course ??
	creation_date = models.DateTimeField(auto_now_add = True)
	message = models.TextField()		# the actual message content itself

	# if show is false, means it is deleted
	not_deleted = models.BooleanField(default = True) 

	def __unicode__(self):
		return self.message

SOL/Forum/views.py
# Create your views here.
from Forum.models import *
from Main.models import Course
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User
from SOL.Student.views import *



# choose which topic to view
def topic_display(request, department, class_number, year, semester, section):

	user = request.user
	current_course = getClassObject(department, class_number, year, semester, section, user)

	# list all topics of a course
	topics = Topics.objects.filter(course = current_course.cid, not_deleted=True)
	classUrl = getClassUrl(current_course)
	
	# see if instructor or current user which means they are allowed to remove their posts
	instructors = getInsts(current_course.cid)
	tas = getTas(current_course.cid)	

	if request.method == 'POST':
		if len(str(request.POST['title'])) <=1 or len(str(request.POST['message'])) <=1:
			error_message = "Please make sure all fields are filled."


			content = getContent(current_course, user)
			content['error_message'] = error_message
			content['topics'] = topics
			content['classUrl'] = classUrl
			content['instAccess'] = instAccess(instructors, tas, user)

			return render_to_response("forum/topic_display.html", content, context_instance=RequestContext(request))

		else: 

			user_topic = Topics(topic_name = request.POST['title'], course = current_course)
			user_topic.save()

			new_topic = Topics.objects.get(topic_name = request.POST['title'], course=current_course, id=user_topic.id)

			# use new topic id that was just created
			user_post = Messages(topic = new_topic, user = request.user, message = request.POST['message'])
			user_post.save()

			return HttpResponseRedirect(classUrl+"forum/")

	content = getContent(current_course, user)
	content['topics'] = topics
	content['classUrl'] = classUrl
	content['instAccess'] = instAccess(instructors, tas, user)

	return render_to_response("forum/topic_display.html", content, context_instance=RequestContext(request))


# list out all messages for that course
def message_display(request, department, class_number, year, semester, section, topic_id):
# no more course_id or topic_id 

	# get all the msgs relating to the specific topic_id
	msgs = Messages.objects.filter(topic = topic_id)

	user = request.user
	current_course = getClassObject(department, class_number, year, semester, section, user)

	# this is for inserting post into database (see below)
	# use course_id and topic_id as a superkey
	current_topic = Topics.objects.get(course = current_course, id = topic_id)

	classUrl = getClassUrl(current_course)

	# see if instructor or current user which means they are allowed to remove their posts
	instructors = getInsts(current_course.cid)
	tas = getTas(current_course.cid)	


	if request.method == 'POST':
		if len(str(request.POST['message'])) <=1:
			error_message = "Please fill out the message box before hitting Submit."

			content = getContent(current_course, user)
			content['messages'] = msgs
			content['classUrl'] = classUrl
			content['error_message'] = error_message
			content['topic'] = current_topic
			content['instAccess'] = instAccess(instructors, tas, user)

			return render_to_response("forum/message_display.html", content, context_instance=RequestContext(request))

		else: 
			user_post = Messages(topic = current_topic, user = request.user, message = request.POST['message'])
			user_post.save()
			return HttpResponseRedirect(classUrl+"forum/" + topic_id)

	instructors = getInsts(current_course.cid)
	tas = getTas(current_course.cid)	

	content = getContent(current_course, user)
	content['messages'] = msgs
	content['classUrl'] = classUrl
	content['topic'] = current_topic
	content['instAccess'] = instAccess(instructors, tas, user)

	return render_to_response("forum/message_display.html", content, context_instance=RequestContext(request))


def remove_topic(request, department, class_number, year, semester, section, topic_id):
	user = request.user


	current_course = getClassObject(department, class_number, year, semester, section, user)
	current_topic = Topics.objects.get(course = current_course, id = topic_id)

	current_topic.not_deleted = False
	current_topic.save()

	classUrl = getClassUrl(current_course)

	return HttpResponseRedirect(classUrl+"forum/")

SOL/templates/forum/message_display.html
{% extends "student/index.html" %}

{% block student %}
	{%if isCurrent %}
		<h2 class="title"> Messages for Topic "{{ topic.topic_name }}"</h2>
		<p class="linkButton"><a href="{{ classUrl }}forum">Back To Topic</a></p>
		<div class="table">	
			{% for msg in messages %}
				{% if msg.not_deleted %}
					<div class="fieldWrapper">
						<span class="fieldLeft">Response # {{ forloop.counter }}</span>
						<span class="fieldRight"></span>
						<span class="fieldLeft">Date:</span>
						<span class="fieldRight"> {{ msg.creation_date }}</span>
						<span class="fieldLeft">Name:</span>
						<span class="fieldRight">{{ msg.user }}</span>
						<span class="fieldLeft">Message: </span>
						<span class="fieldRight">{{ msg.message }}</span>	
					</div>
				{% endif %}
			{% endfor %}


			<form action ="" method="POST">
			{% csrf_token %}
				<div class="fieldWrapper">
					<div class="fieldLeft">Post Message:</div> 
					<div class="fieldRight"><textarea row="5" col="120" name="message"></textarea></div>
					<div class="fieldRight">{% if error_message %} {{ error_message }} {% endif %}</div>
				</div>	
					<div class="submit"><input type="submit" value="Submit" /></div>
			</form>

		</div>
	{% endif %}
{% endblock %}

SOL/templates/forum/topic_display.html
{% extends "student/index.html" %}

{% block student %}
	{%if isCurrent %}
	<h2 class='title'>Current Topics</h2>
	<div class="table">
	{% if topics.count > 0 %}
		{% for topic in topics %}
			<strong><a href="{{ classUrl }}forum/{{ topic.id }}/">{{ topic.topic_name|title }}</a></strong>
			{% for msg in topic.messages_set.all %}
				{% if forloop.last %}
					<br>Recent post by <strong>{{ msg.user }}</strong> at {{ msg.creation_date }}
					{% if instAccess %}
						<br>
						<span class="linkButton"><a href="{{ classUrl}}forum/{{ topic.id }}/delete/">Remove</a></span>
					{% endif %}
					<br>
					{% endif %}
			{% endfor %}
			<br>
		{% endfor %}
	{% else %}
		There are no topics to display.
	{% endif %}
	</div>

	<div class="table">
		<form action ="" method="POST">
		{% csrf_token %}
			<div class="sylWrapper">
				<div class="fieldLeft">Topic Title:</div>
				<div class="fieldRight"> <input type="text" name="title" /></div>
				<div class="fieldLeft">Message:</div>
				<div class="fieldRight"><textarea row="4" col="240" name="message"></textarea></div>
			</div>
				<div class="fieldRight">{% if error_message %} {{ error_message }} {% endif %}</div>
				<div class="submit"><input type="submit" value="Submit" /></div>
		</form>
	</div>
	
	{% endif %}
{% endblock %}