SOL/Instructor/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout

urlpatterns = patterns('Instructor.views',
	url(r'^$', 'index'),
	url(r'^edit', 'greeting'),
	url(r'^syllabus/$', 'syllabus'),
	url(r'^syllabus/update/(?P<sid>\d+)$', 'updateSyllabus'),
	url(r'^activity/(?P<aid>\d+)/remove$', 'removeActivity'),
	url(r'^activity/(?P<aid>\d+)/submissions$', 'getSubmissions'),
	url(r'^activity/(?P<aid>\d+)$', 'updateActivity'),
	url(r'^activity/$', 'activity'),
	url(r'^announcement/(?P<anid>\d+)/remove$', 'removeAnnouncement'),
	url(r'^announcement/(?P<anid>\d+)$', 'updateAnnouncement'),
	url(r'^announcement/$', 'announcement'),
	url(r'^roster/$', 'roster'),
	url(r'^grades/$', 'grades'),
	url(r'^grades/file/$', 'grades_files'),
	url(r'^grades/form/$', 'grades_form'),
	url(r'^grades/form/(?P<aid>\d+)$', 'grades_input'),
	url(r'^slides/$', 'slides'),
	url(r'^slides/(?P<slid>\d+)/update$', 'updateSlides'),
	url(r'^slides/(?P<slid>\d+)/remove$', 'removeSlides'),
	url(r'^quiz/create/$', 'quizCreate'),
	url(r'^quiz/questions/(?P<qid>\d+)/$', 'quizQuestions'),
	url(r'^quiz/delete/(?P<qid>\d+)/$', 'quizRemove'),
	url(r'^quiz/update/(?P<qid>\d+)/$', 'quizUpdate'),
	url(r'^quiz/grades/(?P<qid>\d+)/$', 'quizGrades'),
)

SOL/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', include('Main.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),

	url(r'^accounts/', include('Main.urls')),
	
	url(r'^calendar/', include('Calendar.urls')),
		
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/instructor/', include('Instructor.urls')),
	
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/grades/', include('Gradebook.urls')),
		
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/forum/', include('Forum.urls')),
	
	url(r'^course/(?P<department>[a-zA-z]+)/(?P<class_number>\d+)/(?P<year>\d+)/(?P<semester>[a-zA-z]+)/(?P<section>[a-zA-z]\d{3})/', include('Student.urls')),


)

SOL/Instructor/models.py
#Instructor Model
from django.db import models
from Main.models import UserProfile, Course
from django.forms.models import ModelChoiceField
import os

#Syllabus
class CourseContent(models.Model):
	cid = models.ForeignKey(Course, verbose_name="Course")
	officeHrs = models.CharField(max_length=128, verbose_name="Office Hours")
	officeLocation = models.CharField(max_length=128, verbose_name="Office Location")
	phoneNumber = models.CharField(max_length=12, verbose_name="Phone Number")
	TaOfficeLocation = models.CharField(max_length=128, verbose_name="TA Office Location")
	TaOfficeHrs = models.CharField(max_length=128, verbose_name="TA's Ofice Hours")
	lectTime = models.CharField(max_length=128, verbose_name="Lecture Time")
	prereq = models.CharField(max_length=128, verbose_name="Prerequisites")
	books = models.TextField(verbose_name="Books")
	topics = models.TextField(verbose_name="Topics Covered")
	markingScheme = models.TextField(verbose_name="Marking Scheme")
	academicHonesty = models.TextField(verbose_name="Academic Honesty")
	additionalInfo = models.TextField(blank=True, verbose_name="Additional Info")
	created_on = models.DateTimeField()
	was_updated = models.BooleanField(default=0)
	updated_on = models.DateTimeField()

class Greeting(models.Model):
	cid = models.ForeignKey(Course, verbose_name="Course")
	message = models.TextField(verbose_name="Greeting")
	
class Quiz(models.Model):
	cid = models.ForeignKey(Course, verbose_name="Course")
	name = models.CharField(max_length=256)
	start_date = models.DateTimeField(verbose_name="Start Date")
	end_date = models.DateTimeField(verbose_name="End Date")
	student_attempts = models.IntegerField(verbose_name="Student Attempts")
	def __unicode__(self):
		return self.name

class QuizQuestion(models.Model):
	ANSWER_CHOICES = (
		(0, u'A'),
		(1, u'B'),
		(2, u'C'),
		(3, u'D'),
	)
	qid = models.ForeignKey(Quiz, verbose_name="Quiz")
	question = models.CharField(max_length=512)
	option1 = models.CharField(max_length=512, verbose_name="Option A")
	option2 = models.CharField(max_length=512, verbose_name="Option B")
	option3 = models.CharField(max_length=512, verbose_name="Option C")
	option4 = models.CharField(max_length=512, verbose_name="Option D")
	answer = models.IntegerField(choices=ANSWER_CHOICES)

def get_slide_path(instance, file_name):
	course = instance.cid

	year = str(course.year)
	semester = course.semester
	department = course.department
	class_number = course.class_number
	section = course.section

	return os.path.join('slides', year, semester, department, class_number, section, file_name)

class Slide(models.Model):
	#slide is the lecture notes
	cid = models.ForeignKey(Course, verbose_name="Course")
	title = models.CharField(max_length=128)
	uploaded_on = models.DateTimeField()
	file_path = models.FileField(upload_to=get_slide_path, verbose_name="Select File")

class Activity(models.Model):
	# Activity is an assn, midterm, exam, checkpoint, etc of a course
	STATUS_CHOICES = (
		(0, u'Not Marked'),
		(1, u'Marked but not Released'),
		(2, u'Marked and Released'),
	)
	
	FILE_TYPES = (
		(u'No Submission', u'No Submission'),
		(u'.pdf', u'Portable Document Format (.pdf)'),
		(u'.doc', u'Word 2003 Document (.doc)'),
		(u'.docx', u'Word 2007,2010 Document (.docx)'),
		(u'.txt', u'Text Document (.txt)'),
		(u'.zip', u'Multiple Documents (.zip)'),
	)
	
	aid = models.AutoField(primary_key=True)
	cid = models.ForeignKey(Course, verbose_name="Class")
	activity_name = models.CharField(max_length=256, verbose_name="Activity Name")
	out_of = models.DecimalField(decimal_places=2, max_digits=5)
	worth = models.IntegerField()
	due_date = models.DateTimeField()
	submission_file_type = models.CharField(max_length=64, choices=FILE_TYPES)
	description = models.TextField(blank=True)
	description_doc = models.FileField(upload_to='descriptions', blank=True, verbose_name="Add Description")
	status = models.IntegerField(choices=STATUS_CHOICES)
	released = models.BooleanField(default=False)
	def __unicode__(self):
		return u"%s"%self.cid+" "+self.activity_name
	
class Announcement(models.Model):
	# messages from instructor/TA that will show up on site
	anid = models.AutoField(primary_key=True)
	cid = models.ForeignKey(Course, verbose_name='Class')
	uid = models.ForeignKey(UserProfile, verbose_name='User', related_name='uid')
	title = models.CharField(max_length=256)
	content = models.TextField()
	date_posted = models.DateTimeField()
	send_email = models.BooleanField(default=False, verbose_name="Send Email?")
	was_updated = models.BooleanField(default=0)
	updated_by = models.ForeignKey(UserProfile, related_name='updated_by')
	updated_on = models.DateTimeField(blank=True)
	
class AnnounceRead(models.Model):
	# makes note of whether an annoucement is read or not
	anid = models.ForeignKey(Announcement)
	uid = models.ForeignKey(UserProfile)
	read = models.BooleanField()
	
class ActivityModelChoiceField(ModelChoiceField):
	def label_from_instance(self, obj):
		return obj.name
		
#class Content (CMS??????)

SOL/Instructor/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from Main.models import Course, ClassList
from Main.views import checkFileType, checkFileSize
from Instructor.models import Announcement, Activity, CourseContent, Slide, Greeting, Quiz, QuizQuestion
from Gradebook.models import Grade, UploadGrade, DownloadGrade, OnlineGrade
from Calendar.models import Event, Label
from Calendar.views import getClassLabel
from Student.models import Submission
from Student.views import instAccess, getInsts, getTas, getStudents, getClassUrl, getEnrolled, studentAccess, getAnnouncements, currentSemester, getClassObject, getClassList, QuizAttempt
from forms import AnnounceForm, ActivityForm, CourseForm, GradeForm, SlideForm, GreetingsForm, QuizForm
from decimal import Decimal, getcontext
from django.forms.models import modelformset_factory
from django.forms.formsets import formset_factory
from django.contrib.auth.models import User
from Main.models import UserProfile
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.db.models import Max
import datetime, xlrd, xlwt, re, zipfile, os, time
from django import forms
from datetime import timedelta

#View to generate the page for the main view of Instructor App
def index(request, department, class_number, year, semester, section):
	user = request.user
	c = getClassObject(department, class_number, year, semester, section, user)
	
	content = getContent(c, user)
	return render_to_response('instructor/index.html', content,
		context_instance=RequestContext(request))

#Lets the instructor add a greeting for the main class view
def greeting(request, department, class_number, year, semester, section):
	user = request.user
	c = getClassObject(department, class_number, year, semester, section, user)
	
	message = ''
	classUrl = getClassUrl(c)
	
	#Updates the greeting
	if request.method == 'POST':
		greeting = Greeting(cid=c)
		form = GreetingsForm(request.POST, instance=greeting)
		if form.is_valid():
			try:
				Greeting.objects.get(cid=c.cid)
				update = Greeting.objects.filter(cid=c.cid).update(message=form.cleaned_data["message"])
			except Greeting.DoesNotExist:
				form.save()
			message = 'You have successfully updated the course greeting.'
	else:
		#Initializes the form if a custom message exists, otherwise uses generic message.
		try:
			greet = Greeting.objects.get(cid=c.cid)
			form = GreetingsForm(initial={'message': greet.message,})
		except Greeting.DoesNotExist:
			greet = "I would like to welcome you all to "+c.department+" "+c.class_number+".  I look forward to this semester and I hope you all have fun and enjoy."
			form = GreetingsForm(initial={'message': greet,})
	
	content = getContent(c, user)
	content['form'] = form
	content['classUrl'] = classUrl
	content['message'] = message
	return render_to_response('instructor/greeting.html', content, 
		context_instance=RequestContext(request))

#View to generate the page for the syllabus view of Instructor App
def syllabus(request, department, class_number, year, semester, section):
	user = request.user
	c = getClassObject(department, class_number, year, semester, section, user)
	
	message = ''
	classUrl = getClassUrl(c)

	#Form that has defined fields for prof to fill out to create a syllabus
	if request.method == 'POST':
		content = CourseContent(cid=c, created_on=datetime.datetime.now(), was_updated=0, updated_on=datetime.datetime.now() )
		form = CourseForm(request.POST, instance=content)
		if form.is_valid():
			form.save()
			message = 'You have successfully created a syllabus'
	else:
		#If form exists, redirect to update page, otherwise send blank form
		try:
			course = CourseContent.objects.get(cid=c.cid)
			return HttpResponseRedirect(classUrl+"instructor/syllabus/update/%s" %course.id)
		except CourseContent.DoesNotExist:
			form = CourseForm()
	
	content = getContent(c, user)
	content['form'] = form
	content['message'] = message
	return render_to_response('instructor/syllabus.html', content, 
		context_instance=RequestContext(request))

#View to update the graded syllabus in the Instructor App
def updateSyllabus(request, department, class_number, year, semester, section, sid):
	user = request.user
	c = getClassObject(department, class_number, year, semester, section, user)
	s = get_object_or_404(CourseContent, pk=sid)
	
	message = ''
	classUrl = getClassUrl(c)
	#Updates the syllabus
	if request.method == 'POST':
		course = CourseContent(id=sid, cid=c, created_on=s.created_on, was_updated=1, updated_on=datetime.datetime.now() )
		form = CourseForm(request.POST, instance=course)
		if form.is_valid():
			form.save()
			message = 'You have successfully updated the syllabus'
	else:
		#Initializes the form with existing syllabus information
		course = CourseContent.objects.get(cid=c.cid)
		form = CourseForm(initial={'officeHrs': course.officeHrs, 'officeLocation': course.officeLocation, 'phoneNumber': course.phoneNumber, 'TaOfficeLocation': course.TaOfficeLocation, 'TaOfficeHrs': course.TaOfficeHrs, 'lectTime': course.lectTime, 'prereq': course.prereq, 'books': course.books, 'topics': course.topics, 'markingScheme': course.markingScheme, 'academicHonesty': course.academicHonesty, 'additionalInfo': course.additionalInfo,})
	
	content = getContent(c, user)
	content['form'] = form
	content['classUrl'] = classUrl
	content['message'] = message
	return render_to_response('instructor/syllabus.html', content, 
		context_instance=RequestContext(request))

#Allows the instructor to add lecture slides
def slides(request, department, class_number, year, semester, section):
	# slides are just lecture notes
	user = request.user
	c = getClassObject(department, class_number, year, semester, section, user)
	error_message = ''
	slides = Slide.objects.filter(cid=c.cid)
	
	#Uploads the slide file and adds to database
	if request.method == 'POST':
		slide = Slide(cid=c, uploaded_on=datetime.datetime.now())
		form = SlideForm(request.POST, request.FILES, instance=slide)
		if form.is_valid():
			# Verify file type and size (8MB max)
			uploaded_file = request.FILES['file_path']
			max_file_size = 16777216
			file_types_allowed = ['.pdf', '.doc', '.docx', '.ppt', '.pptx', '.txt', '.zip']
			isProperFileType = checkFileType(uploaded_file, file_types_allowed)
			isProperFileSize = checkFileSize(uploaded_file, max_file_size)
			if isProperFileType and isProperFileSize:
				submit_slide = Slide(cid=c, title=form.cleaned_data['title'], uploaded_on=datetime.datetime.now())
				submitted_file = request.FILES['file_path']
				submit_slide.file_path.save(submitted_file.name, submitted_file)
				return HttpResponseRedirect("")
			elif not isProperFileType:
				error_message = "Error: File type is incorrect - must be one of .pdf, .doc, .docx, .ppt, .pptx, .txt, or .zip"
			elif not isProperFileSize:
				error_message = "Error: File size exceeds the max of 8MB"
	else:
		form = SlideForm()
		
	content = getContent(c, user)
	content['form'] = form
	content['slides'] = slides
	content['error_message'] = error_message
	return render_to_response('instructor/slides.html', content, 
		context_instance=RequestContext(request))
	
#Updates the slides
def updateSlides(request, department, class_number, year, semester, section, slid):
	user = request.user
	c = getClassObject(department, class_number, year, semester, section, user)
	
	#Makes sure the slide exists, otherwise return 404
	s = get_object_or_404(Slide, pk=slid)

	slides = Slide.objects.filter(cid=c.cid)
	
	classUrl = getClassUrl(c)
	#Updates the slide file and in the database
	if request.method == 'POST':
		slide = Slide(cid=c, uploaded_on=datetime.datetime.now(), id=slid)
		form = SlideForm(request.POST, request.FILES, instance=slide)
		if form.is_valid():
			form.save()
			url = classUrl +'instructor/slides'
			return HttpResponseRedirect(url)
	else:
		#Initializes the form
		form = SlideForm(initial={'title': s.title, 'file_path': s.file_path})
	
	content = getContent(c, user)
	content['form'] = form
	content['slides'] = slides
	return render_to_response('instructor/slides.html', content, 
		context_instance=RequestContext(request))
		
#Deletes the slide from the database
def removeSlides(request, department, class_number, year, semester, section, slid):
	user = request.user
	c = getClassObject(department, class_number, year, semester, section, user)
	
	#Makes sure the slide exists, otherwise return 404
	s = get_object_or_404(Slide, pk=slid)
	accessToInst = instAccess(getInsts(c.cid), getTas(c.cid), user)

	classUrl = getClassUrl(c)
	if accessToInst:
		slide = Slide.objects.get(id=slid)
		slide.delete()
		url = classUrl + 'instructor/slides'
		return HttpResponseRedirect(url)
	else:
		content = {'accessToInst': accessToInst, 'classUrl': classUrl}
		return render_to_response('instructor/slides.html', content, 
			context_instance=RequestContext(request))
			
#View to generate the page for the graded activities view of Instructor App
def activity(request, department, class_number, year, semester, section):
	user = request.user
	c = getClassObject(department, class_number, year, semester, section, user)
	
	#Gets the list of students for want to receive email notifications for graded activities
	emailStudents = UserProfile.objects.filter(classlist__cid=c.cid, setting__email_activity=1)

	activities = Activity.objects.filter(cid=c.cid).order_by('due_date')
	
	if request.method == 'POST':
		activity = Activity(cid=c, released=0)
		form = ActivityForm(request.POST, request.FILES, instance=activity)
		if form.is_valid():
			if form.cleaned_data['status'] == 2:
				form.cleaned_data["released"] = 1
			else:
				form.cleaned_data["released"] = 0
			form.save()
			
			#Create a calendar event for each activity created

SOL/templates/instructor/activity.html
{% extends "instructor/index.html" %}
{% block head %}
	<link type="text/css" href="{{ STATIC_URL }}css/timepicker.css" rel="Stylesheet" />
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>
{% endblock %}
{% block instructorcontent %}
	<script type="text/javascript">
		$(function() {
	    	$('#id_due_date').datetimepicker({
				dateFormat: "yy-mm-dd"
			});
		});
	</script>

	{% if update %}
		<h2 class="title">Activity Update Form</h2>
	{% else %}
		<h2 class="title">Activity Creation Form</h2>
	{% endif %}
	
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="table">
			{% for field in form %}
			<div class="fieldWrapper">
				<div class="fieldLeft">
					{{ field.label_tag }}: 
				</div>
				<div class="fieldRight">
					{{ field.errors }}
					{{ field }}
				</div>
			</div>
			{% endfor %}
			<div class="submit">
				{% if update %}
					<input type="submit" value="Update Activity">
				{% else %}
					<input type="submit" value="Create Activity">
				{% endif %}
			</div>
		</div>
	</form>
	
	<div class="bottomPosts">
		<h2 class="title">Current Activities</h2>
		{% for activity in activities %}
			<div class="table">
				<div class="actWrapper">
					<span class="actLeft">Activity Name: </span>
					<span class="actRight">{{ activity.activity_name }}</span>
				</div>
				<div class="actWrapper">
					<span class="actLeft">Out Of: </span>
					<span class="actRight">{{ activity.out_of }}</span>
				</div>
				<div class="actWrapper">
					<span class="actLeft">Worth: </span>
					<span class="actRight">{{ activity.worth }}%</span>
				</div>
				<div class="actWrapper">
					<span class="actLeft">Due Date: </span>
					<span class="actRight">{{ activity.due_date }}</span>
				</div>
				{% if activity.description %}
				<div class="actWrapper">
					<span class="actLeft">Description: </span>
					<span class="actRight">
						{{ activity.description|linebreaksbr }}
						{% if activity.description_doc %}
							<br />
							<a href="{{ MEDIA_URL }}{{ activity.description_doc }}">View Description</a>
						{% endif %}
					</span>
				</div>
				{% else %}
					{% if activity.description_doc %}
						<div class="actWrapper">
							<span class="actLeft">Description: </span>
							<span class="actRight">
									<a href="{{ MEDIA_URL }}{{ activity.description_doc }}">View Description</a>
							</span>
						</div>
					{% endif %}
				{% endif %}
				<div class="actWrapper">
					<span class="actLeft">Status: </span>
					<span class="actRight">
						{% if activity.status == 0 %}
							Not Marked
						{% else %}
							{% if activity.status == 1 %}
								Marked but not released
							{% else %}
								Marked and released
							{% endif %}
						{% endif %}
					</span>
				</div>
				<div class="actWrapper">
					<span class="actLeft">Actions: </span>
					<span class="actRight">
						<span class="postLinks">
							<span class="linkButton"><a href="{{ activity.aid }}">Edit</a></span> 
							<span class="linkButton"><a href="{{ activity.aid }}/remove">Remove</a></span> 
							<span class="linkButton"><a href="{{ activity.aid }}/submissions">Download Submissions</a></span> 
						</span>
					</span>
				</div>
				<div class="endAct"></div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

SOL/templates/instructor/announcement.html
{% extends "instructor/index.html" %}

{% block instructorcontent %}
	<h2 class="title">Post An Announcement</h2>
	<form action="" method="POST">
		<div class="table">
		{% csrf_token %}
			{% for field in form %}
			<div class="fieldWrapper">
				<div class="fieldLeft">
					{{ field.label_tag }} 
				</div>
					<div class="fieldRight">
						{{ field.errors }}
						{{ field }}
					</div>
			</div>
			{% endfor %}
			<div class="submit">
				<input type="submit" value="Submit">
			</div>
		</div>
	</form>
	<div class="bottomPosts">
		<h2 class="title">Past Announcements</h2>
		{% for announcement in announcements %}
			<div class="table">
				<div class="postTop">
					<strong>{{ announcement.title }}</strong> 
					<span class="postDate">(
					{% if flavour == "full" %}
						{{ announcement.date_posted }} 
					{% else %}
						{{ announcement.date_posted|date:"Y-m-d h:i" }} 
					{% endif %}
					{% if announcement.was_updated == 1 %}
						Updated on: 
						{% if flavour == "full" %}
							{{ announcement.updated_on }} 
						{% else %}
							{{ announcement.updated_on|date:"Y-m-d h:i" }}
						{% endif %}
						By: {{ announcement.updated_by.user.first_name }} {{ announcement.updated_by.user.last_name }}
					{% endif %}
					)
					</span>
					<span class="postLinks">
						<span class="linkButton"><a href="{{ announcement.anid }}">Edit</a></span> 
						<span class="linkButton"><a href="{{ announcement.anid }}/remove">Remove</a></span>
					</span>
				</div>
				<div class="postBottom">
					{{ announcement.content }}
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

SOL/templates/instructor/emailActivityTemplate.html
<html>
<head>

</head>
<body>
	<h3>{{ activity.activity_name }} Grade Released in {{ class.department }} {{ class.class_number }}</h3>
	<strong>Activity Name:</strong> {{ activity.activity_name }}<br/>
	Click Here to <a href="http://cmpt470.csil.sfu.ca:8012/course/{{ class.department }}/{{ class.class_number }}/{{ class.year }}/{{ class.semester}}/{{ class.section}}/grades/{{ activity.aid }}/">View Grade</a>
</body>
</html>

SOL/templates/instructor/emailAnnounceTemplate.html
<html>
<head>
</head>
<body>
	<h3>New Announcement in {{ class.department }} {{ class.class_number }}</h3>
	<div id="table">
		<div id="postTop">
			<strong>{{ title }}</strong> 
			<span class="postDate">({{ date_posted }}) </span>
		</div>
		
		<div id="postBottom">
			{{ content }}
		</div>
	</div>
	<a href="http://cmpt470.csil.sfu.ca:8012/course/{{ class.department }}/{{ class.class_number }}/{{ class.year }}/{{ class.semester}}/{{ class.section}}/announcements/">
</body>
</html>

SOL/templates/instructor/grades.html
{% extends "instructor/index.html" %}
{% block instructorcontent %}
    <h2 class="title">Input Student Grades</h2>
    <ul>
		<li><a href="file/">Manage student grades via Excel Files</a></li>
		<li><a href="form/">Manage student grades via Online Form</a></li>
	</ul>

{% endblock %}

SOL/templates/instructor/quizCreate.html
{% extends "instructor/index.html" %}

{% block head %}
<link type="text/css" href="{{ STATIC_URL }}css/timepicker.css" rel="Stylesheet" />
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript">
	$(function() {
    	$('#id_start_date, #id_end_date').datetimepicker({
			dateFormat: "yy-mm-dd"
		});
	});
</script>
{% endblock %}

{% block instructorcontent %}
	<h2 class="title">Create Quiz</h2>
	<form action="" method="POST">
		<div class="table">
			{% csrf_token %}
			{% for field in form %}
			<div class="fieldWrapper">
				<div class="fieldSylLeft">
					{{ field.label_tag }}: 
				</div>
					<div class="fieldSylRight">
						{{ field.errors }}
						{{ field }}
					</div>
			</div>
			{% endfor %}
			<div class="submit">
				<input type="submit" value="Submit">
			</div>
		</div>
	</form>
	
	<div class="bottomPosts">
		<h2 class="title">Quizzes</h2>
		{% for quiz in quizzes %}
			<div class="table">
				<div class="actWrapper">
					<span class="actLeft">{{ quiz.name }}</span>
					<span class="actRight">
						<span class="linkButton"><a href="{{ classUrl }}instructor/quiz/questions/{{ quiz.id }}">Add Questions</a></span>  
						<span class="linkButton"><a href="{{ classUrl }}instructor/quiz/delete/{{ quiz.id }}">Remove</a></span>
						<span class="linkButton"><a href="{{ classUrl }}instructor/quiz/update/{{ quiz.id }}">Update</a></span>
						<span class="linkButton"><a href="{{ classUrl }}instructor/quiz/grades/{{ quiz.id }}">View Grades</a></span>
					</span>
				</div>
				<div class="endAct"></div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

SOL/templates/instructor/quizGrades.html
{% extends "instructor/index.html" %}
{% block instructorcontent %}
	<h2 class="title">Quiz Grades</h2>
	<p class="linkButton"><a href="{{ classUrl }}instructor/quiz/create/">Back to Quiz</a></p>
	<div class="table">
		<h3 class="title">{{ quiz.name }} Results</h3>
		<table border=0 width=700>
			<tr>
				<td><strong>Last Name</strong></td>
				<td><strong>First Name</strong></td>
				<td><strong>SFU ID</strong></td>
				<td><strong>Result</strong></td>
			</tr>
			{% for student in students %}
				<tr>
					<td>{{ student.user.last_name }}</td>
					<td>{{ student.user.first_name }}</td>
					<td>{{ student.sfu_id }}</td>
					<td>
						{% if student.grade %}
							{{ student.grade.result__max }}/{{ out_of }}
						{% else %}
							None
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}